config/routes.rb
Rails.application.routes.draw do

  root 'cocktails#index'

  resources :cocktails

  get 'godmode'   => 'intelligent_design#index'
  post 'godmode'  => 'intelligent_design#concoct'

  get 'darwin' => 'evolution#index'
  post 'darwin' => 'evolution#evolve'

  namespace :admin do
    resources :cocktails, only: [:new, :create]
    resources :ingredients
    resources :groups, path: :categories
  end
  get 'admin' => 'admin#index'
end

app/models/cocktail.rb
class Cocktail < ActiveRecord::Base
  belongs_to :drinkware

  has_many :recipes
  has_many :ingredients, through: :recipes

  validates_presence_of :name

  serialize :ingredient_id_array, Array

  before_save :set_ingredient_id_array

  MIN_EVOLUTION_INGREDIENTS_IN_COMMON = 1

  class << self
    def requiring(ingredient_ids)
      return nil if ingredient_ids.blank?
      filter_cocktails(ingredient_ids)
    end

    def evolve(ingredient_ids, from_cocktail_id = nil)
      return nil if ingredient_ids.blank?
      evolve_cocktails(ingredient_ids, from_cocktail_id)
    end

  private

    def filter_cocktails(ingredient_ids)
      filtered = []
      Cocktail.all.each do |candidate|
        is_a_subset = (candidate.ingredient_id_array & ingredient_ids).size.eql?(candidate.ingredient_id_array.size)
        filtered << candidate if is_a_subset
      end
      filtered
    end

    def evolve_cocktails(ingredient_ids, from_cocktail_id)
      evolved = []
      Cocktail.all.each do |candidate|
        in_common = (candidate.ingredient_id_array & ingredient_ids).size
        not_same = !(candidate.ingredient_id_array.size.eql?(in_common))
        passes_min_in_common = in_common >= MIN_EVOLUTION_INGREDIENTS_IN_COMMON
        more_ingredients = candidate.ingredient_id_array.size > ingredient_ids.size
        if more_ingredients && passes_min_in_common && not_same && candidate.id != from_cocktail_id
          evolved << { cocktail: candidate, in_common: in_common, num_ingredients: candidate.ingredient_id_array.size }
        end
      end
      select_evolved_cocktails(evolved)
    end

    def select_evolved_cocktails(evolved_cocktails)
      return evolved_cocktails.map{ |hsh| hsh[:cocktail] } if evolved_cocktails.size <= 3
      selected = get_max_in_common(evolved_cocktails)
      selected = get_min_additional(evolved_cocktails, selected)
      get_random(evolved_cocktails, selected)
    end

    # Gets max in common with min number of new ingredients
    def get_max_in_common(evolved_cocktails)
      sorted = evolved_cocktails.sort { |a, b| [b[:in_common], a[:num_ingredients]] <=> [a[:in_common], b[:num_ingredients]] }
      [sorted.first[:cocktail]].compact
    end

    # Gets another cocktail with a minimal amount of new ingedients
    def get_min_additional(evolved_cocktails, selected)
      sorted = evolved_cocktails.sort_by { |hsh| hsh[:num_ingredients] }
      if selected.index(sorted.first[:cocktail]).nil?
        selected << sorted.first[:cocktail]
      else
        selected << sorted.second[:cocktail]
      end
      selected
    end

    # Gets a random cocktail from the candidate list
    def get_random(evolved_cocktails, selected)
      return selected if evolved_cocktails.size <= selected.size
      while true
        sampled = evolved_cocktails.sample
        if selected.index(sampled[:cocktail]).nil?
          selected << sampled[:cocktail]
          return selected
        end
      end
    end

  end

  def set_ingredient_id_array
    current_ingredient_array = []
    ingredients.each do |ingredient|
      current_ingredient_array << ingredient.id
    end
    self.ingredient_id_array = current_ingredient_array
  end

end

app/controllers/admin/cocktails_controller.rb
class Admin::CocktailsController < ApplicationController

  def new
  end

  def create
    Importer.load_string(params[:yaml])
    redirect_to new_admin_cocktail_path, message: 'Success!'
  end

end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  layout false
end

app/helpers/admin/cocktails_helper.rb
module Admin::CocktailsHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/views/cocktails/_cocktail.html.erb
<h2><%= cocktail.name %></h2>

<h3>Ingredients</h3>
  <ul>
    <% cocktail.recipes.each do |recipe| %>
      <li><%= recipe.ingredient.name %>, <%= recipe.measurement %></li>
    <% end %>
  </ul>

<% if cocktail.drinkware %>
<h3>Drinkware</h3>
<p>Serve in a <%= cocktail.drinkware.name %></p>
<% end %>

<% if cocktail.garnish %>
<h3>Garnish</h3>
<p><%= cocktail.garnish %></p>
<% end %>

<% if cocktail.instructions %>
<h3>Instructions</h3>
<p><%= cocktail.instructions %></p>
<% end %>

app/views/cocktails/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
    <!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
    <!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
    <!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Cocktails</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

    <!-- Serif -->
    <link href='http://fonts.googleapis.com/css?family=Vollkorn:400italic,700italic,400,700' rel='stylesheet' type='text/css'>
    <!-- Sans-Serif -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,800,400' rel='stylesheet' type='text/css'>

  </head>

  <body>
    <!--[if lt IE 7]>
        <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    <div class="main container">
      <!-- Columns are always 50% wide, on mobile and desktop -->
      <div class="row" style="position: relative; white-space: nowrap;">
        <%= link_to '', darwin_path, id: 'evolution' %><%= link_to '', godmode_path, id: 'intelligent-design' %>
        <%= image_tag 'cocktails-circled.png', style: 'position: absolute; top: 319px; left: 448px;' %>
      </div>
    </div>
  </body>
</html>