config/routes.rb
Rails.application.routes.draw do

  root 'cocktails#index'

  resources :cocktails

  get 'godmode'   => 'intelligent_design#index'
  post 'godmode'  => 'intelligent_design#concoct'

  get 'darwin' => 'evolution#index'
  post 'darwin' => 'evolution#evolve'

  namespace :admin do
    resources :cocktails, only: [:new, :create]
    resources :ingredients
    resources :groups, path: :categories
  end
  get 'admin' => 'admin#index'
end

app/models/bar.rb
class Bar < ActiveRecord::Base
  belongs_to :user
  belongs_to :ingredient

  validates_presence_of :user
  validates_presence_of :ingredient
end

app/models/cocktail.rb
class Cocktail < ActiveRecord::Base
  belongs_to :drinkware

  has_many :recipes
  has_many :ingredients, through: :recipes

  validates_presence_of :name

  serialize :ingredient_id_array, Array

  before_save :set_ingredient_id_array

  MIN_EVOLUTION_INGREDIENTS_IN_COMMON = 1

  class << self
    def requiring(ingredient_ids)
      return nil if ingredient_ids.blank?
      filter_cocktails(ingredient_ids)
    end

    def evolve(ingredient_ids, from_cocktail_id = nil)
      return nil if ingredient_ids.blank?
      evolve_cocktails(ingredient_ids, from_cocktail_id)
    end

  private

    def filter_cocktails(ingredient_ids)
      filtered = []
      Cocktail.all.each do |candidate|
        is_a_subset = (candidate.ingredient_id_array & ingredient_ids).size.eql?(candidate.ingredient_id_array.size)
        filtered << candidate if is_a_subset
      end
      filtered
    end

    def evolve_cocktails(ingredient_ids, from_cocktail_id)
      evolved = []
      Cocktail.all.each do |candidate|
        in_common = (candidate.ingredient_id_array & ingredient_ids).size
        not_same = !(candidate.ingredient_id_array.size.eql?(in_common))
        passes_min_in_common = in_common >= MIN_EVOLUTION_INGREDIENTS_IN_COMMON
        more_ingredients = candidate.ingredient_id_array.size > ingredient_ids.size
        if more_ingredients && passes_min_in_common && not_same && candidate.id != from_cocktail_id
          evolved << { cocktail: candidate, in_common: in_common, num_ingredients: candidate.ingredient_id_array.size }
        end
      end
      select_evolved_cocktails(evolved)
    end

    def select_evolved_cocktails(evolved_cocktails)
      return evolved_cocktails.map{ |hsh| hsh[:cocktail] } if evolved_cocktails.size <= 3
      selected = get_max_in_common(evolved_cocktails)
      selected = get_min_additional(evolved_cocktails, selected)
      get_random(evolved_cocktails, selected)
    end

    # Gets max in common with min number of new ingredients
    def get_max_in_common(evolved_cocktails)
      sorted = evolved_cocktails.sort { |a, b| [b[:in_common], a[:num_ingredients]] <=> [a[:in_common], b[:num_ingredients]] }
      [sorted.first[:cocktail]].compact
    end

    # Gets another cocktail with a minimal amount of new ingedients
    def get_min_additional(evolved_cocktails, selected)
      sorted = evolved_cocktails.sort_by { |hsh| hsh[:num_ingredients] }
      if selected.index(sorted.first[:cocktail]).nil?
        selected << sorted.first[:cocktail]
      else
        selected << sorted.second[:cocktail]
      end
      selected
    end

    # Gets a random cocktail from the candidate list
    def get_random(evolved_cocktails, selected)
      return selected if evolved_cocktails.size <= selected.size
      while true
        sampled = evolved_cocktails.sample
        if selected.index(sampled[:cocktail]).nil?
          selected << sampled[:cocktail]
          return selected
        end
      end
    end

  end

  def set_ingredient_id_array
    current_ingredient_array = []
    ingredients.each do |ingredient|
      current_ingredient_array << ingredient.id
    end
    self.ingredient_id_array = current_ingredient_array
  end

end

app/models/drinkware.rb
class Drinkware < ActiveRecord::Base
  validates_presence_of :name
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :cocktail
end

app/models/group.rb
class Group < ActiveRecord::Base
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :group

  has_many :recipes
  has_many :cocktails, through: :recipes

  validates_presence_of :name
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :cocktail
  belongs_to :ingredient

  validates_presence_of :cocktail
  validates_presence_of :ingredient
  validates_presence_of :measurement
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :bars, dependent: :destroy
  has_many :ingredients, through: :bars

  def self.new_guest
    new { |u| u.guest = true }
  end

  def name
    guest ? "Guest" : username
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :current_or_guest_user

  # if user is logged in, return current_user, else return guest_user
  def current_or_guest_user
    if @current_user
      if session[:guest_user_id] && session[:guest_user_id] != @current_user.id
        guest_user(with_retry = false).try(:destroy)
        session[:guest_user_id] = nil
      end
      @current_user
    else
      guest_user
    end
  end

  # find guest_user object associated with the current session,
  # creating one as needed
  def guest_user(with_retry = true)
    # Cache the value the first time it's gotten.
    @cached_guest_user ||= User.find(session[:guest_user_id] ||= create_guest_user.id)

  rescue ActiveRecord::RecordNotFound # if session[:guest_user_id] invalid
    session[:guest_user_id] = nil
    guest_user if with_retry
  end

  private

  # login action here to set current user

  def create_guest_user
    u = User.new_guest
    u.save!(:validate => false)
    session[:guest_user_id] = u.id
    u
  end
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  layout false
end

app/controllers/evolution_controller.rb
class EvolutionController < ApplicationController

  def index
    @base_groups = Group.where(:evolvable => true).to_a
  end

  def evolve
    if(params[:base])
      ing    = Ingredient.where(:group_id => params[:base]).to_a.sample
      drinks = Cocktail.evolve([ing.id])

      render json: {
        drinks: drinks,
        html: render_to_string(partial: 'evolution', locals: { drinks: drinks }, layout: false)
      }
    else
      ings   = Cocktail.find(params[:cocktail]).ingredients.map { |i| i.id }
      drinks = Cocktail.evolve(ings, params[:cocktail])

      render json: {
        drinks: drinks,
        html: render_to_string(partial: 'evolution', locals: { drinks: drinks }, layout: false)
      }
    end
  end
end

app/controllers/intelligent_design_controller.rb
class IntelligentDesignController < ApplicationController
  def index
    @ingredients = Ingredient.order(:name)
    @saved_ingredients = current_or_guest_user.ingredients.map { |i| i.id }
  end

  def concoct
    drinks = Cocktail.requiring(params[:ingredients].map(&:to_i))
    ing_ids = params[:ingredients] unless params[:ingredients].blank?
    current_or_guest_user.ingredients = Ingredient.find(ing_ids)
    render json: {
      drinks: drinks, # Returning this in json incase we wanna fuck with it on the front-end.
      html: render_to_string(partial: 'drinks', locals: { drinks: drinks }, layout: false)
    }
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/cocktails_helper.rb
module Admin::CocktailsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/evolution_helper.rb
module EvolutionHelper
end

app/helpers/intelligent_design_helper.rb
module IntelligentDesignHelper
  def saved_ingredient?(ing_id)
    return @saved_ingredients.include? ing_id unless @saved_ingredients.blank?
  end
end

app/views/admin/index.html.erb
<h1>Admin</h1>
<h2><%= link_to 'Cocktails', new_admin_cocktail_path %></h2>
<h2><%= link_to 'Ingredients', admin_ingredients_path %></h2>
<h2><%= link_to 'Groups', admin_groups_path %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>

  <head>
    <!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
    <!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
    <!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
    <!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Cocktails</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

    <!-- Serif -->
    <link href='http://fonts.googleapis.com/css?family=Vollkorn:400italic,700italic,400,700' rel='stylesheet' type='text/css'>
    <!-- Sans-Serif -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,800,400' rel='stylesheet' type='text/css'>
  </head>

  <body>
    <!--[if lt IE 7]>
        <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    <header>
      <div class="container">
        <h1 class="title"><a href="/">Cocktail Evolution!</a></h1>
      </div>
    </header>

    <div class="main container">
      <%= yield %>
    </div>

    <footer>
      <div class="container">
        <p>Created by Sepcot, Ning, Rob &amp; Jesse.</p>
        <p>Copyright &copy; 2014 Cocktail. All rights reserved.</p>
      </div>
    </footer>

    <script type="text/javascript">
      var rumbleBannerBackgroundColor, rumbleBannerTextColor, rumbleBannerLinkColor, rumbleBannerPlacement;
      rumbleBannerBackgroundColor = "#161616";
      rumbleBannerTextColor = "#b0b0b0";
      rumbleBannerLinkColor = "#ffffff";
      rumbleBannerPlacement = "bottom"; // Optionally replace with "top".
    </script>
    <script src="https://d4nnn7wspfa3h.cloudfront.net/banner-2014.js" type="text/javascript"></script>

  </body>

</html>