config/routes.rb
Rails.application.routes.draw do

  root 'cocktails#index'

  resources :cocktails

  get 'godmode'   => 'intelligent_design#index'
  post 'godmode'  => 'intelligent_design#concoct'

  get 'darwin' => 'evolution#index'
  post 'darwin' => 'evolution#evolve'

  namespace :admin do
    resources :cocktails, only: [:new, :create]
    resources :ingredients
    resources :groups, path: :categories
  end
  get 'admin' => 'admin#index'
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :group

  has_many :recipes
  has_many :cocktails, through: :recipes

  validates_presence_of :name
end

app/controllers/admin/ingredients_controller.rb
class Admin::IngredientsController < ApplicationController

  def index
  end

  def show
  end

  def new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)

    @ingredient.save ? redirect_to(admin_ingredients_path) : render(:new)
  end

  def edit
  end

  def update
    ingredient.update_attributes(ingredient_params) ? redirect_to(admin_ingredients_path) : render(:edit)
  end

private

  def ingredient_params
    params.require(:ingredient).permit(:name, :group_id)
  end

  def ingredient
    @ingredient ||= params[:id].present? ? Ingredient.find(params[:id]) : Ingredient.new
  end
  helper_method :ingredient

  def ingredients
    @ingredients ||= Ingredient.order(:name).page(params[:page])
  end

  helper_method :ingredients
end

app/helpers/admin/ingredients_helper.rb
module Admin::IngredientsHelper
end

app/views/admin/ingredients/_form.html.erb
<%= form_for [:admin, ingredient], html: { multipart: true } do |f| %>
  <%= f.label :name %> <%= f.text_field :name %><br />
  <%= f.label :group_id %> <%= f.select :group_id, Group.order(:name).all.map {|g| [g.name, g.id] }, include_blank: true %><br />
  <%= f.submit %>
<% end %>

app/views/admin/ingredients/_ingredient.html.erb
<%= link_to ingredient.name, edit_admin_ingredient_path(ingredient) %>

app/views/admin/ingredients/edit.html.erb
<h1>Edit Ingredient</h1>

<%= render 'form' %>

app/views/admin/ingredients/index.html.erb
<h1>Ingredients</h1>

<p><%= link_to 'Create Ingredient', new_admin_ingredient_path %></p>

<ul>
<% ingredients.each do |ingredient| %>
  <li><%= render ingredient %></li>
<% end %>
</ul>

<%= paginate ingredients %>

app/views/admin/ingredients/new.html.erb
<h1>Create a Ingredient</h1>

<%= render 'form' %>