config/routes.rb
Rails.application.routes.draw do

  root 'cocktails#index'

  resources :cocktails

  get 'godmode'   => 'intelligent_design#index'
  post 'godmode'  => 'intelligent_design#concoct'

  get 'darwin' => 'evolution#index'
  post 'darwin' => 'evolution#evolve'

  namespace :admin do
    resources :cocktails, only: [:new, :create]
    resources :ingredients
    resources :groups, path: :categories
  end
  get 'admin' => 'admin#index'
end

app/models/group.rb
class Group < ActiveRecord::Base
end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < ApplicationController

  def index
  end

  def show
  end

  def new
  end

  def create
    @group = Group.new(group_params)

    @group.save ? redirect_to(admin_groups_path) : render(:new)
  end

  def edit
  end

  def update
    group.update_attributes(group_params) ? redirect_to(admin_groups_path) : render(:edit)
  end

private

  def group_params
    params.require(:group).permit(:name, :evolvable)
  end

  def group
    @group ||= params[:id].present? ? Group.find(params[:id]) : Group.new
  end
  helper_method :group

  def groups
    @groups ||= Group.order(:name).page(params[:page])
  end
  helper_method :groups

end

app/views/admin/groups/_form.html.erb
<%= form_for [:admin, group], html: { multipart: true } do |f| %>
  <%= f.label :name %> <%= f.text_field :name %><br />
  <%= f.check_box :evolvable %> <%= f.label :evolvable %><br />
  <%= f.submit %>
<% end %>

app/views/admin/groups/_group.html.erb
<%= link_to group.name, edit_admin_group_path(group) %>

app/views/admin/groups/edit.html.erb
<h1>Edit Group</h1>

<%= render 'form' %>

app/views/admin/groups/index.html.erb
<h1>Groups</h1>

<p><%= link_to 'Create Group', new_admin_group_path %></p>

<ul>
<% groups.each do |group| %>
  <li><%= render group %></li>
<% end %>
</ul>

<%= paginate groups %>

app/views/admin/groups/new.html.erb
<h1>Create a Group</h1>

<%= render 'form' %>